# image will be published to ghcr.io/<user>/<name>
name: hachiman
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    - type: files
      files:
          - source: system
            destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

    - from-file: common/rpm-ostree/rpm-ostree.yml
    - from-file: common/rpm-ostree/gnome-base.yml
    - from-file: roles/laptop-user.yml

    - type: justfiles
      validate: true
      include:
          - custom.just

    - type: akmods
      base: main # if not specified, classic "main" base is used by default
      install:
          - framework-laptop
          - ryzen-smu
          - v4l2loopback

    - type: systemd
      system:
          enabled:
              - power-profiles-daemon.service
          masked:
              - tlp.service
      user:
          enabled:
              - podman.socket

    - type: signing # this sets up the proper policy & signing files for signed images to work fully
