modules: # configured multiple times to highlight how options are overridden
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - app.devsuite.Ptyxis
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - dev.geopjr.Collision
        - io.gitlab.librewolf-community
        - io.missioncenter.MissionCenter
        - org.mozilla.firefox
        - org.gnome.Calculator
        - org.gnome.DejaDup
        - org.gnome.Epiphany
        - org.gnome.Extensions
        - org.gnome.Firmware
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
      remove:
        - org.gnome.eog
    user:
      repo-name: flathub
