# image will be published to ghcr.io/<user>/<name>
name: hachiman 
# description will be included in the image's metadata
description: Image for AMD based Framework Laptop.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  # Enable just until ppd 0.2 hits stable repo
  - type: script
    scripts:
      - install_testing_ppd.sh

  - type: systemd
    system:
      enabled:
        - power-profiles-daemon.service
      masked:
        - tlp.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # Media Apps
        - org.pitivi.Pitivi
        - org.pitivi.Pitivi.Codecs
        - org.gimp.GIMP
        - com.makemkv.MakeMKV
        - com.spotify.Client
        - com.github.iwalton3.jellyfin-media-player
        - org.videolan.VLC
        - io.lmms.LMMS
        - com.obsproject.Studio
        - fr.handbrake.ghb
        # Computing Apps
        - org.mozilla.firefox
        - md.obsidian.Obsidian
        - org.gnome.Recipes
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Contacts
        - org.gnome.Evince
        - org.gnome.Logs
        - org.gnome.Todo
        - org.gnome.NautilusPreviewer
        - org.gnome.SimpleScan
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.font-viewer
        - org.signal.Signal
        - com.slack.Slack
        - org.gnome.DejaDup
        - com.brave.Browser
        - com.discordapp.Discord
        - org.libreoffice.LibreOffice
        - org.gnome.Weather
        - org.gnome.Firmware
        - org.gnome.Loupe
        - com.transmissionbt.Transmission
        - com.mattjakeman.ExtensionManager
        - com.thincast.client
        # Developemnt Apps
        - org.zealdocs.Zeal
        - org.gnome.Boxes
        - org.gnome.Builder
        - com.github.marhkb.Pods
        - io.podman_desktop.PodmanDesktop
        - com.vscodium.codium
        - re.sonny.Workbench
        # Games
        - org.gnome.Reversi
        - org.gnome.Mahjongg
        - com.play0ad.zeroad
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

